#ifndef SETRACE_GENL_FAMILY_H
#define SETRACE_GENL_FAMILY_H

#define SETRACE_GENL_VERSION_NR 1
#define SETRACE_GENL_NAME "SETRACE"

enum {
	SETRACE_ATTR_UNSPEC,
	SETRACE_ATTR_MSG,
	SETRACE_ATTR_ID,
	__SETRACE_ATTR_MAX
};

#define SETRACE_ATTR_MAX (__SETRACE_ATTR_MAX - 1)

enum {
	SETRACE_CMD_UNSPEC,
	SETRACE_CMD_SUB,
	SETRACE_CMD_UNSUB,
	SETRACE_CMD_EVENT,
	__SETRACE_CMD_MAX
};

#define SETRACE_CMD_MAX (__SETRACE_CMD_MAX - 1)

#endif
